ALTER TABLE ES_STATE ADD VERSION VARCHAR(255) NULL;

GO

ALTER TABLE ES_MACHINE ADD VERSION VARCHAR(255) NULL;

GO

/****** Object:  Table [dbo].[ES_VERSION]    Script Date: 10/28/2013 15:17:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ES_VERSION](
	[ID] [int] NOT NULL,
	[DESCRIPTIF] [varchar](255) NULL,
	[FILENAME] [varchar](255) NOT NULL,
 CONSTRAINT [PK_ES_VERSION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[ES_VERSIONMACHINE]    Script Date: 10/28/2013 15:53:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ES_VERSIONMACHINE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MACHINE_ID] [int] NOT NULL,
	[DATEACTION] [datetime] NOT NULL,
	[VERSION] [varchar](255) NOT NULL,
	[ISOK] [bit] NULL,
	[LASTINDEXCALL] [int] NOT NULL,
 CONSTRAINT [PK_ES_VERSIONMACHINE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

UPDATE ES_MACHINE SET VERSION = 'V0';

GO